import { StyleSheet, Dimensions } from 'react-native';
import { useThemeContext } from '@/context/ThemeProvider';
import { Colors } from '@/constants/Colors';

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;
const createGlobalStyles = (colorScheme) =>
    StyleSheet.create({
        header: {
            width: '100%',
            position: 'absolute',
            padding: 30,
            paddingTop: screenHeight * 0.08,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            zIndex: 100,
            backgroundColor: Colors[colorScheme].background,
        },
        backIcon: {
            position: 'absolute',
            top: 50,
            left: 20,
            zIndex: 10,
            padding: 6,
            backgroundColor: 'rgba(0,0,0,0.5)',
            borderRadius: 40,
        },
        image: {
            width: '100%',
            height: '100%',
        },
        titleContainer: {
            flexShrink: 1,
            justifyContent: 'center',
        },
        buttonContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: 10,
            flexShrink: 0,
        },
        smallprofileImage: {
            width: 28,
            height: 28,
            borderRadius: 14,
            overflow: 'hidden',
            justifyContent: 'center',
            alignItems: 'center',
        },
        profileImage: {
            width: 120,
            height: 120,
            borderRadius: 60,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            overflow: 'hidden',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: Colors[colorScheme].pri,
            marginBottom: 10,
            marginRight: 30,
        },
        tabBar: {
            position: 'absolute',
            bottom: 30,
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 60,
            paddingHorizontal: 30,
            marginHorizontal: 30,
            flexDirection: 'row',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            borderTopWidth: 0,
            elevation: 0,
            borderTopColor: 'transparent',
        },
        container: {
            paddingTop: screenHeight * 0.14,
            height: screenHeight,
            justifyContent: 'flex-start',
        },
        profileContainer: {
            justifyContent: 'flex-start',
            height: screenHeight,
        },
        itemContainer: {
            width: screenWidth * 0.9,
            alignSelf: 'center',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 20,
        },
        attractionsContainer: {
            marginLeft: screenWidth * 0.05,
            gap: 15,
            paddingRight: screenWidth * 0.05,
        },
        heroImage: {
            height: screenHeight * 0.29,
            borderRadius: 20,
            marginBottom: 20,
            alignSelf: 'center',
            overflow: 'hidden',
        },
        imageShawdow: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            paddingVertical: 15,
            paddingHorizontal: 15,
            backgroundColor: 'rgba(0,0,0,0.4)',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        buttonCard: {
            backgroundColor: Colors[colorScheme].pri,
            width: '100%',
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        buttonCardIcon: {
            width: 80,
            height: 80,
            borderRadius: 40,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 15,
            overflow: 'hidden',
        },
        buttonLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        overlay: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'rgba(0,0,0,0.5)',
        },
        overlayContent: {
            maxHeight: screenHeight * 0.6,
            width: screenWidth * 0.8,
            backgroundColor: Colors[colorScheme].pri,
            padding: 20,
            borderRadius: 12,
            alignSelf: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 10,
        },
        overlaybg: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0
        },
        overlayCloseButton: {
            position: 'absolute',
            top: 60,
            right: 20,
            zIndex: 10,
        },
        thinInputTextBox: {
            paddingVertical: 10,
            paddingHorizontal: 30,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: Colors[colorScheme].pri,
            fontSize: 18,
            color: Colors[colorScheme].highlight,
        },
        inputTextBox: {
            width: '100%',
            marginVertical: 10,
            paddingVertical: 20,
            paddingHorizontal: 30,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: Colors[colorScheme].pri,
            fontSize: 18,
            color: Colors[colorScheme].highlight,
        },
        smallButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].sec,
            borderRadius: 40,
            height: 30,
            width: 40,
            borderWidth: 1,
            borderColor: Colors[colorScheme].highlight,
            alignItems: 'center',
            justifyContent: 'center',
            marginHorizontal: 5,
        },
        smallPillButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 40,
            width: screenWidth * 0.3,
            alignItems: 'center',
            justifyContent: 'center',
        },
        pillButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 60,
            bottom: 30,
            width: '100%',
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            borderTopWidth: 0,
        },
        categoryContainer: {
            flexDirection: 'row',
            paddingHorizontal: 24,
            gap: 12,
            alignItems: 'center',
            height: 40,
            marginVertical: 20
        },
        categoryButton: {
            flexDirection: 'row',
            gap: 5,
            alignItems: 'center',
            paddingVertical: 6,
            paddingHorizontal: 12,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: 'transparent',
        },
        categoryButtonSelected: {
            backgroundColor: Colors[colorScheme].highlight,
        },
        shopItemContainer: {
            marginBottom: 60,
            height: screenHeight - 240,
            marginHorizontal: 30
        },
        productCard: {
            borderRadius: 20,
            marginBottom: 20,
            alignSelf: 'center',
            overflow: 'hidden',
            width: screenWidth * 0.4,
            backgroundColor: Colors[colorScheme].pri,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        productCardContent: {
            flex: 1,
            marginHorizontal: 10,
            paddingBottom: 10,
            backgroundColor: Colors[colorScheme].pri
        },
        attractionImageContainer: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 300,
        },
        infoCard: {
            marginTop: -40,
            backgroundColor: Colors[colorScheme].pri,
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            padding: 20,
            gap: 15,
            zIndex: 20,

        },
        rating: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#FEF3C7',
            paddingHorizontal: 8,
            borderRadius: 16,
            gap: 4,
            padding: 3,
        },
        facilityGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            marginTop: 10,
        },
        longDivider: {
            height: 1.5,
            width: '100%',
            backgroundColor: Colors[colorScheme].highlight,
            marginVertical: 20,
        },
        divider: {
            height: 1,
            width: '100%',
            backgroundColor: Colors[colorScheme].highlight,
            marginVertical: 10,
        },
        selectorGroup: {
            flex: 1,
            marginRight: 12,
        },
        sizeRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
        },
        colorRow: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            marginRight: 10,
            marginTop: 6,
        },
        quantityInline: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
        },
        cartButton: {
            marginTop: 24,
            paddingVertical: 14,
            paddingHorizontal: 20,
            borderRadius: 12,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: '#ccc',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
            elevation: 2,
        },
        cartText: {
            fontWeight: '600',
            fontSize: 16,
        },
        cartOverlay: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            width: screenWidth,
            height: screenHeight * 0.6,
            backgroundColor: Colors[colorScheme].pri,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: -4 },
            shadowOpacity: 0.4,
            shadowRadius: 8,
            elevation: 10,
            padding: 20,
        }
    });

export const useGlobalStyles = () => {
    const { theme } = useThemeContext();
    return createGlobalStyles(theme);
};
