import { StyleSheet, Dimensions } from 'react-native';
import { useThemeContext } from '@/context/ThemeProvider';
import { Colors } from '@/constants/Colors';
import { useEffect, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '@/firebaseConfig';
import AttractionList from '@/app/profile/admin/attractions';
import { attractions } from '@/context/allItems';

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;
const createGlobalStyles = (colorScheme) =>
    StyleSheet.create({
        header: {
            width: '100%',
            position: 'absolute',
            padding: 30,
            marginTop: screenHeight * 0.05,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            zIndex: 100,
        },
        image: {
            width: '100%',
            height: '100%',
        },
        titleContainer: {
            flexShrink: 1,
            justifyContent: 'center',
        },
        buttonContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: 10,
            flexShrink: 0,
        },
        smallprofileImage: {
            width: 28,
            height: 28,
            borderRadius: 14,
            overflow: 'hidden',
            justifyContent: 'center',
            alignItems: 'center',
        },
        profileImage: {
            width: 120,
            height: 120,
            borderRadius: 60,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            overflow: 'hidden',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: Colors[colorScheme].pri,
            marginBottom: 10,
            marginRight: 30,
        },
        tabBar: {
            position: 'absolute',
            bottom: 30,
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 60,
            paddingHorizontal: 30,
            marginHorizontal: 30,
            flexDirection: 'row',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            borderTopWidth: 0,
            elevation: 0,
            borderTopColor: 'transparent',
        },
        container: {
            paddingTop: screenHeight * 0.13,
            height: screenHeight,
            justifyContent: 'flex-start',
        },
        profileContainer: {
            justifyContent: 'flex-start',
            height: screenHeight,
        },
        itemContainer: {
            width: screenWidth * 0.9,
            alignSelf: 'center',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 20,
        },
        attractionsContainer: {
            marginLeft: screenWidth * 0.05,
            gap: 15,
            paddingRight: screenWidth * 0.05,
        },
        heroImage: {
            height: screenHeight * 0.29,
            borderRadius: 20,
            marginBottom: 20,
            alignSelf: 'center',
            overflow: 'hidden',
        },
        imageShawdow: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            paddingVertical: 15,
            paddingHorizontal: 15,
            backgroundColor: 'rgba(0,0,0,0.4)',
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        buttonCard: {
            backgroundColor: Colors[colorScheme].pri,
            width: '100%',
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        buttonCardIcon: {
            width: 80,
            height: 80,
            borderRadius: 40,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 15,
            overflow: 'hidden',
        },
        buttonLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: Colors[colorScheme].pri,
            gap: 8,
        },
        overlay: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'rgba(0,0,0,0.5)',
        },
        overlayContent: {
            maxHeight: screenHeight * 0.6,
            width: screenWidth * 0.8,
            backgroundColor: Colors[colorScheme].pri,
            padding: 20,
            borderRadius: 12,
            alignSelf: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 10,
        },
        overlaybg: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0
        },
        overlayCloseButton: {
            position: 'absolute',
            top: 60,
            right: 20,
            zIndex: 10,
        },
        thinInputTextBox: {
            paddingVertical: 10,
            paddingHorizontal: 30,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: Colors[colorScheme].pri,
            fontSize: 18,
            color: Colors[colorScheme].highlight,
        },
        inputTextBox: {
            paddingVertical: 20,
            paddingHorizontal: 30,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: Colors[colorScheme].pri,
            fontSize: 18,
            color: Colors[colorScheme].highlight,
        },
        smallPillButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 40,
            width: screenWidth * 0.3,
            alignItems: 'center',
            justifyContent: 'center',
        },
        smallButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 40,
            width: 200,
            alignItems: 'center',
            justifyContent: 'center',
        },
        pillButton: {
            position: 'relative',
            backgroundColor: Colors[colorScheme].highlight,
            borderRadius: 40,
            height: 60,
            bottom: 30,
            width: '90%',
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 5 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            borderTopWidth: 0,
        },
        categoryContainer: {
            flexDirection: 'row',
            paddingHorizontal: 22,
            gap: 12,
            alignItems: 'center',
            height: 40,
            marginBottom: 20
        },
        categoryButton: {
            flexDirection: 'row',
            gap: 5,
            alignItems: 'center',
            paddingVertical: 6,
            paddingHorizontal: 12,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: Colors[colorScheme].highlight,
            backgroundColor: 'transparent',
        },
        categoryButtonSelected: {
            backgroundColor: Colors[colorScheme].highlight,
        },
        shopItemContainer: {
            marginBottom: 60,
            height: screenHeight - 240,
            marginHorizontal: 26
        },
        productCard: {
            height: screenHeight * 0.29,
            borderRadius: 20,
            marginBottom: 20,
            alignSelf: 'center',
            overflow: 'hidden',
            width: Dimensions.get('window').width * 0.42,
            backgroundColor: Colors[colorScheme].pri,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        productCardContent: {
            marginHorizontal: 10,
            paddingBottom: 10,
            backgroundColor: Colors[colorScheme].pri
        },
    });

export const useGlobalStyles = () => {
    const { theme } = useThemeContext();
    return createGlobalStyles(theme);
};
